### ISSUE TITLE
Uncaught error

### ISSUE THREAD

**Issue by nmarcionese** [ndimatteo/sanity-plugin-note-field#11]
Hey Matteo - I get the below error when i try to add this plugin to my sanity config/schema. 

The defineField is being added within a defineType type:'document'. 

When i add the defineField, the below error occurs. 

Uncaught error: A component suspended while responding to synchronous input. This will cause the UI to be replaced with a loading indicator. To fix, updates that suspend should be wrapped with startTransition.

[console-export-2024-2-21_12-52-9.txt](https://github.com/ndimatteo/sanity-plugin-note-field/files/14379695/console-export-2024-2-21_12-52-9.txt)

Node: v18.16.0
Sanity: v30.0.0

Any insight would be helpful.

**Comment by ndimatteo** [comment]
Hey there @nmarcionese,

The error you shared doesn't indicate the issue originating from anything with this plugin. It sounds like something else is going on with your setup, but without seeing how the schema file is setup I can't really diagnose the issue for you.

I can confirm this is working just fine on the latest version of the Sanity Studio (`v3.30.0`).

Would you mind sharing more details about your setup?
