### ISSUE TITLE
Upgrade to Sanity Studio v3

### ISSUE THREAD

**Issue by tiago-sanches-bairesdev** [ndimatteo/sanity-plugin-note-field#6]
It would be great to see this plugin be compatible with Sanity Studio v3

**Comment by cavellblood** [comment]
I agree.

**Comment by tiago-sanches-bairesdev** [comment]
@cavellblood  some nice guy actually already did it https://github.com/ndimatteo/sanity-plugin-note-field/pull/5. It just needs to be approved

**Comment by cavellblood** [comment]
@tiago-sanches-bairesdev Ah, perfect! Hadn't checked the PRs.

**Comment by ndimatteo** [comment]
Hey there @cavellblood, @tiago-sanches-bairesdev, and anyone else popping in!

I have immediate plans to update this plugin and the Vercel Deploy plugin to the Sanity Studio V3. I'm hoping to have this updated by the end of the week, but may push to early next week at the latest. Stay tuned, and thanks for your patience!

🤘

**Comment by cavellblood** [comment]
Sounds great! Thank you!

**Comment by FavLucas** [comment]
Hi @ndimatteo,
Any update on that by any chance ?

Thanks !

**Comment by ndimatteo** [comment]
@FavLucas, @cavellblood, @tiago-sanches-bairesdev, and anyone else following: The Studio V3 version of this is now available! 🤘
